/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.keremtigre.CoronaVirusApp;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kerem
 */
public class ListCountriesData extends javax.swing.JFrame {
//1 tane JsonObject oluşturuyoruz
    JsonObject jsonObjectData=new JsonObject();
    //Jtable'ımızın Sütun isimlerini belirtiyoruz.
    String[] columns={"ÜLKE","ÜLKE KODU","YENİ VAKA","TOPLAM VAKA","YENİ ÖLÜM","TOPLAM ÖLÜM","YENİ KURTULAN","TOPLAM KURTULAN","TARİH"};
    public ListCountriesData() {
        initComponents();
        //Pencere kapanınca diğer pencerelerin kapanmasını önler
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        //1 tane JsonObject oluşturuyoruz
    JsonObject jsonObjectData=new JsonObject();
    //Jtable'ımızın Sütun isimlerini belirtiyoruz.
    String[] columns={"ÜLKE","ÜLKE KODU","YENİ VAKA","TOPLAM VAKA","YENİ ÖLÜM","TOPLAM ÖLÜM","YENİ KURTULAN","TOPLAM KURTULAN","TARİH"};
        //Frame'in Ortalanacığını belirtiyoruz.
        setLocationRelativeTo(this);
        //CoronaVirusData classından bir nesne oluşturuyoruz.
             CoronaVirusData getData= new CoronaVirusData();
        try {
            //CoronaVirusData classındaki getCoronaVirusData() methodundan return ettiğimiz objeyi alıyoruz
        jsonObjectData=getData.getCoronaVirusData();
        //Objenin içindeki jsonArrayı alıyoruz
        JsonArray jarray = jsonObjectData.getAsJsonArray("Countries"); 
        //JTable için verilerimizi oluşturuyoruz
        Object[][] data=new Object[jarray.size()][columns.length];
        //Çekeceğimiz Veriler için String Değişkenler Oluşturuyoruz
        String Country;
        String CountryCode;
        String NewConfirmed;
        String TotalConfirmed;
        String NewDeaths;
        String TotalDeaths;
        String TotalRecovered;
        String NewRecovered;
         String Date;
      
            
            for (int i = 0; i < jarray.size(); i++) {
                
            
    //Burada Çektiğimiz verileri oluşturduğumuz String değişkenlere atıyoruz
                jsonObjectData=jarray.get(i).getAsJsonObject();
         Country=jsonObjectData.get("Country").toString();
         CountryCode=jsonObjectData.get("CountryCode").toString(); 
         NewConfirmed=jsonObjectData.get("NewConfirmed").toString();
         TotalConfirmed=jsonObjectData.get("TotalConfirmed").toString();
         NewDeaths=jsonObjectData.get("NewDeaths").toString();
         TotalDeaths=jsonObjectData.get("TotalDeaths").toString();
         NewRecovered=jsonObjectData.get("NewRecovered").toString();
         TotalRecovered=jsonObjectData.get("TotalRecovered").toString();
         Date=jsonObjectData.get("Date").toString();  
          
          //Burada ise verileri jtable aktaracağımız data isimli 2*2 matrise atıyoruz
                data[i][0]=Country;
                data[i][1]=CountryCode;
                data[i][2]=NewConfirmed;
                data[i][3]=TotalConfirmed;
                data[i][4]=NewDeaths;
                data[i][5]=TotalDeaths;
                data[i][6]=NewRecovered;
                data[i][7]=TotalRecovered;
                 data[i][8]=Date;
                
            }
            
            
       //Bu kısımda ise çektiğimiz verileri JTable a yerleştirdik.
        DefaultTableModel model=new DefaultTableModel(data,columns);
        jTable1.setModel(model);
    } catch (Exception ex) {
        //hata çıkmasında durumda kullanıcıyı bilgilendiriyoruz
       JOptionPane.showMessageDialog(null, "Veriler çekilirken hata oluştu. Hata web servisinden kaynaklı olabilir. Lütfen tekrar deneyiniz.");
           
        
    }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1283, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Burada ise kullanıcın jTable değişiklik yapmasını engelliyoruz
        boolean click=jTable1.isEditing();
        JOptionPane.showMessageDialog(null, "Verileri Değiştiremezsiniz");
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListCountriesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListCountriesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListCountriesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListCountriesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListCountriesData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
